# Generated by Django 5.0.6 on 2024-06-11 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=200)),
                ('project_name', models.CharField(max_length=200)),
                ('developer', models.CharField(max_length=200)),
                ('completion_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Properties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('place', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='property_images')),
                ('is_off_plan', models.BooleanField(default=False)),
                ('payment_plan', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('APARTMENTS', 'apartments'), ('VILLAS', 'villas'), ('TOWNHOUSES', 'townhouses')], max_length=100)),
                ('details', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.propertydetails')),
            ],
        ),
    ]
