# Generated by Django 5.0.6 on 2024-06-11 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_properties_description_alter_properties_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='properties',
            name='details',
        ),
        migrations.AddField(
            model_name='propertydetails',
            name='property',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.properties'),
        ),
    ]
