# Generated by Django 5.0.6 on 2024-06-11 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_remove_properties_details_propertydetails_property'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertydetails',
            name='completion_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='propertydetails',
            name='developer',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='propertydetails',
            name='location',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='propertydetails',
            name='project_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
