# Generated by Django 5.0.6 on 2024-06-11 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_propertydetails_completion_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties',
            name='type',
            field=models.CharField(choices=[('duplex', 'duplex'), ('penthouse', 'penthouse')], max_length=100, null=True),
        ),
    ]
