# Generated by Django 5.0.6 on 2024-06-11 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_properties_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='category',
            field=models.CharField(choices=[('apartments', 'APARTMENTS'), ('villas', 'VILLAS'), ('townhouses', 'TOWNHOUSES')], max_length=100),
        ),
    ]
