# Generated by Django 5.0.6 on 2024-06-11 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_properties_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='category',
            field=models.CharField(choices=[('apartments', 'apartments'), ('villas', 'villas'), ('townhouses', 'townhouses')], max_length=100),
        ),
    ]
