# Generated by Django 5.0.6 on 2024-06-12 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_propertydetails_property'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertydetails',
            name='completion_date',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
