# Generated by Django 5.0.6 on 2024-06-12 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_alter_propertydetails_completion_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(choices=[('district one', 'district one'), ('palm jumerirah', 'palm jumerirah'), ('downtown', 'downtown'), ('dubai marina', 'dubai marina'), ('dubai creek harbour', 'dubai creek harbour'), ('business bay', 'business bay')], max_length=100)),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='properties',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.location'),
        ),
    ]
