# Generated by Django 5.0.6 on 2024-06-12 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_location_properties_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='image',
            field=models.ImageField(null=True, upload_to='media/place_photo'),
        ),
    ]
