# Generated by Django 5.0.6 on 2024-06-12 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_location_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdetails',
            name='during_construction',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='paymentdetails',
            name='on_booking',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='paymentdetails',
            name='property',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_details', to='account.properties'),
        ),
        migrations.AddField(
            model_name='paymentdetails',
            name='upon_handover',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='place',
            field=models.CharField(choices=[('district one', 'district one'), ('palm jumeirah', 'palm jumeirah'), ('downtown', 'downtown'), ('dubai marina', 'dubai marina'), ('dubai creek harbour', 'dubai creek harbour'), ('business bay', 'business bay')], max_length=100),
        ),
    ]
