# Generated by Django 5.0.6 on 2024-06-12 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_paymentdetails_during_construction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties',
            name='map',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='properties',
            name='video',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
