# Generated by Django 5.0.6 on 2024-06-12 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_alter_properties_map_alter_properties_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='type',
            field=models.CharField(choices=[('duplex', 'duplex'), ('penthouse', 'penthouse')], default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='properties',
            name='video',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
