# Generated by Django 5.0.6 on 2024-06-13 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_alter_properties_map_alter_properties_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
