# Generated by Django 5.0.6 on 2024-06-13 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_properties_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='description',
            field=models.CharField(max_length=30000),
        ),
    ]
