# Generated by Django 5.0.6 on 2024-06-17 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0023_alter_properties_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('no_of_projects', models.IntegerField()),
                ('founded_year', models.IntegerField()),
                ('starting_price', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='properties',
            name='developer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='property', to='account.developer'),
        ),
    ]
