# Generated by Django 5.0.6 on 2024-06-17 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0024_developer_properties_developer'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='image',
            field=models.ImageField(null=True, upload_to='media/developer_images'),
        ),
    ]
