# Generated by Django 5.0.6 on 2024-06-25 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0026_news_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='properties',
            name='is_off_plan',
        ),
        migrations.AddField(
            model_name='properties',
            name='status',
            field=models.CharField(choices=[('completed', 'completed'), ('off plan', 'off plan'), ('ready', 'ready'), ('under construction', 'under construction')], max_length=100, null=True),
        ),
    ]
