# Generated by Django 5.0.6 on 2024-06-28 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0027_remove_properties_is_off_plan_properties_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentdetails',
            name='during_construction',
        ),
        migrations.RemoveField(
            model_name='paymentdetails',
            name='on_booking',
        ),
        migrations.RemoveField(
            model_name='paymentdetails',
            name='upon_handover',
        ),
        migrations.AddField(
            model_name='paymentdetails',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='paymentdetails',
            name='value',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='paymentdetails',
            name='property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_details', to='account.properties'),
        ),
    ]
