# Generated by Django 5.0.6 on 2024-06-28 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0028_remove_paymentdetails_during_construction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdetails',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
